# Site settings
title: Peter Nybergh
author:
  name: Peter Nybergh
  email: peter.w.nybergh@gmail.com
description: "Public page of Peter Nybergh."

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 